# Generated by Django 5.0.1 on 2024-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueloPersonalizado',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('aerolinea', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=80)),
                ('lugar_arribo', models.CharField(max_length=80)),
                ('fecha_salida', models.DateTimeField()),
            ],
            options={
                'db_table': 'Vuelo',
            },
        ),
    ]
