# Generated by Django 5.0.1 on 2024-01-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_vuelopersonalizado'),
        ('reservations', '0002_alter_reserva_vuelo_reservado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vuelo',
        ),
    ]
