# Generated by Django 5.0.1 on 2024-01-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_delete_vuelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelopersonalizado',
            old_name='identificador',
            new_name='id',
        ),
    ]
