# Generated by Django 5.0.1 on 2024-01-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_rename_identificador_vuelopersonalizado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelopersonalizado',
            old_name='destino',
            new_name='c_arribo',
        ),
        migrations.RenameField(
            model_name='vuelopersonalizado',
            old_name='lugar_arribo',
            new_name='c_destino',
        ),
        migrations.RenameField(
            model_name='vuelopersonalizado',
            old_name='fecha_salida',
            new_name='f_salida',
        ),
        migrations.RenameField(
            model_name='vuelopersonalizado',
            old_name='numero_vuelo',
            new_name='numero',
        ),
    ]
