# Generated by Django 5.0.1 on 2024-01-23 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pasajero_reservado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passenger.pasajero')),
                ('vuelo_reservado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.vuelo')),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
    ]
